services:
  learning-db:
    image: postgres
    container_name: git3
    restart: always
    environment:
      POSTGRES_DB: ai_learning_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 556722371
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
