version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: learning-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0556722371
      POSTGRES_DB: ai_learning_platform
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: